### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by brijj2006** [brijj2006/shortlist_resume#3]
To do list for this project

- [ ] Add feasibility to pass pdf and docx file for prediction
- [ ] Add feasibility to pass pdf and docx file for training the model
- [ ] For training the model pass the file containing the resume and ask user input as 0 or 1 as shortlisted flag
- [ ] Create web app for the user to train the model and get the prediction
- [ ] Deploy the application on cloud to make it accessible to the users
- [ ] Calculate the accuracy level of the model
- [ ] Add reporting feature for the predicted resumes
- [ ] Add security
